### ISSUE TITLE
Image is read two times instead of one

### ISSUE THREAD

**Issue by CreaMondes** [gokulkrishh/qrcodescan.in#1]
Hello,

First thank you for the QR Code scanner!
On https://qrcodescan.in/, when I click on the button to take a picture (no use of the video), take a picture and choose ok, the QRCode is read well and the popin appears. But when I click on close, it appears again and I have to close it a second time.

Is it because the qrcode is read two times instead of one ? Or it's just a bug of the popin?

Thank you!

**Comment by gokulkrishh** [comment]
@CreaMondes Thanks!

I tried the same scenario in ios chrome (secretly its safari :P but uses web view of safari ), safari. I am not able to reproduce this.


 Can you tell me which browser, OS, and versions you are using will help me to re-produce and see whats the issue? afaik, when you take pic, it only scan once and when you close we come out of the scan part.

**Comment by CreaMondes** [comment]
Hello,
Thanks for your quick answer!
I just did some tests and this behaviour is only on my computer. It has no cam, and when I select an image, the popin has to be closed two times. Browsers : Firefox 82.0.3 and Chrome  86.0.4240.198, Windows 7. The qrcode is read well.
I don't reproduce with my android smartphone.

**Comment by gokulkrishh** [comment]
@CreaMondes Thanks for the information on the browser and os version.  I will try to fix this when I get time.

**Comment by CreaMondes** [comment]
Thank you! Don't hesitate if you need I test things.

**Comment by gokulkrishh** [comment]
@CreaMondes Fixed this issue, would love to get some feedback. Let me know. Thanks
