### ISSUE TITLE
Support for image upload

### ISSUE THREAD

**Issue by humble-barnacle001** [gokulkrishh/qrcodescan.in#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gokulkrishh** [comment]
@humble-barnacle001 Add more info the issue. 

Issue template has clear cut def of what is needed to create issue. Pls follow it. I am closing this issue for now. Re-open or create one more with more desp.
