### ISSUE TITLE
Website doesn’t read the second QR code

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [gokulkrishh/qrcodescan.in#11]
**Describe the bug**
I use this website to scan the first QR code, then a dialog diaplayed and let me to open the webpage, but after that, the green bar disappeared from qrcodescan.in, and doesn’t work with the second QR code

**To Reproduce**
1. Go to qrcodescan.in
2. Show the first QR code made by 2QR.info
3. Show the second QR code made by 2QR.info

**Expected behavior**
The site should read every QR code as expected

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 87.0

**Smartphone (please complete the following information):**
 - Device: Galaxy S6+ Edge
 - OS: Android 7.0
 - Browser Firefox
 - Version 87.0.0-rc.1

**Additional context**

**Comment by gokulkrishh** [comment]
@KrasnayaPloshchad Yes even i noticed this issue. Will try to fix it over the weekend. 👍

**Comment by KrasnayaPloshchad** [comment]
I think this should be fixed now, tested with both desktop and mobile browser.
Desktop: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0`
Mobile: `Mozilla/5.0 (Android 7.0; Mobile; rv:91.0) Gecko/91.0 Firefox/91.0` (Firefix Nightly)

**Comment by gokulkrishh** [comment]
@KrasnayaPloshchad Can you be a little more clear, is it fixed or you think it will be fixed?

**Comment by KrasnayaPloshchad** [comment]
Yes, I think this should be the same as #14.

**Comment by gokulkrishh** [comment]
@KrasnayaPloshchad Thanks for inputs. So closing this issue.

**Comment by Daltonmedia** [comment]
This seems still the case to me.
Only one code can be scanned, after closing the dialog nothing happens to the second code I scan.
Trying this on safari on ios and macos and on chrome on macos. Can't test on a windows or android machine.
