### ISSUE TITLE
platforms support

### ISSUE THREAD

**Issue by yzy132** [gokulkrishh/qrcodescan.in#13]
hello～
I want to ask if this only supports ios safari？
because I open it in other browsers on ios and it does not support

**Comment by gokulkrishh** [comment]
@yzy132 Read this https://stackoverflow.com/questions/48382150/do-all-browsers-on-ios-use-wkwebview-or-uiwebview

TLDR: Browsers in iOS are safari internally.

**Comment by yzy132** [comment]
Hi～Thanks for your quick reply
But I think you have misunderstood what I mean，It can normal work in ios safari Browser，but it can‘t work in iOS others browsers。

**Comment by gokulkrishh** [comment]
@yzy132 Thats exactly what i understood and replied for. Google it you will find why other browsers in iOS doesnt work.

**Comment by yzy132** [comment]
Ok,thank you very much 😉



发自我的iPhone


------------------ Original ------------------
From: Gokulakrishnan Kalaikovan ***@***.***&gt;
Date: Mon,May 10,2021 9:05 PM
To: gokulkrishh/qrcodescan.in ***@***.***&gt;
Cc: 杨子俞 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [gokulkrishh/qrcodescan.in] platforms support (#13)





 
@yzy132 Thats exactly what i understood and replied for. I have put a wrong link in above comment but Google it you will find why other browsers in iOS doesnt work.
