### ISSUE TITLE
Shapes in re-scan

### ISSUE THREAD

**Issue by SPSpisoft** [gokulkrishh/qrcodescan.in#14]
Hi
In Android - Chrome 90.0.4430.210
The first scan is done well and opens the dialog box, but for the next scan, the scanner gets out of work, while the camera is turned on, the scan pointer is not displayed.

Thanks so much

**Comment by gokulkrishh** [comment]
@SPSpisoft Thanks for reporting. I will check this when i get time.

**Comment by gokulkrishh** [comment]
@SPSpisoft This issue is fixed now, you should be able to scan one after another.
