### ISSUE TITLE
Add iOS splash screen

### ISSUE THREAD

**Issue by hello-smile6** [gokulkrishh/qrcodescan.in#15]
**Is your feature request related to a problem? Please describe.**

Yes. The PWA does not have an iOS splash screen.
**Describe the solution you'd like**
For a splash screen to be generated using https://appsco.pe/developer/splash-screen and incorporated.

**Describe alternatives you've considered**
There are no alternative solutions.

**Additional context**
If this is done, the end result will look like https://crossnote.app/ .

**Comment by gokulkrishh** [comment]
@hello-smile6 This app already has splash screen using `pwacompat`. I dont think we need to replace this.

**Comment by hello-smile6** [comment]
# No. It does not on iOS. I'm not using iOS right now, but I know because there is no way to use a `blob:` URL in the splash screen meta tag.
@gokulkrishh All you need to do is go to [AppScope Splash Screen Generator](https://appsco.pe/developer/splash-screens), drop in the icon, and get it over with. It only takes 5 minutes. Please stop being lazy and do it.

**Comment by gokulkrishh** [comment]
@hello-smile6 App does have slash screen as i am also using iOS. I am not going to add this one .Thanks for suggesting though.
