### ISSUE TITLE
how to use in vueproject as a plugin

### ISSUE THREAD

**Issue by werewolf666** [gokulkrishh/qrcodescan.in#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gokulkrishh** [comment]
@werewolf666 Issues in GitHub are meant for bugs or feature requests in-app should not be used as a help forum. Pls, post your questions in StackOverflow for help.
