### ISSUE TITLE
To include drag and drop feature

### ISSUE THREAD

**Issue by asaugat04** [gokulkrishh/qrcodescan.in#21]
Great application at all! It will be a bit more effective if we can drag and drop image of qr code. 
Would it be possible to add this feature?

**Comment by gokulkrishh** [comment]
@asaugat04 This application is mostly for mobile users but it does work on the desktop as well. So ideally you can select images on desktop or take images with a built-in camera to scan in mobile.

This solves the problem you are talking about. Do you have any specific scenarios in mind? or?

**Comment by asaugat04** [comment]
@gokulkrishh yeah it's ok if your main focus is for mobile.
I am using it in my desktop too and i thought it would be great if i could just drop images directly. That's it☺️

**Comment by gokulkrishh** [comment]
@asaugat04 I see. But selecting the photos option button at the bottom should solve your problem for now. As of now no plan to support drag and drop file support.

**Comment by asaugat04** [comment]
@gokulkrishh It's ok
