### ISSUE TITLE
Problem with links without http

### ISSUE THREAD

**Issue by Aramil-S** [gokulkrishh/qrcodescan.in#3]
**Describe the bug**
When link without http is scanned, "Open" button sometimes appear and sometimes doesn't.
Also when such link is opened, linking don't work correctly. Ie. scanning page.com result in address like qrreaderhost.com/page.com

**To Reproduce**
1. Open scanner
2. Scan link with http
3. Close popup
3. Scan link without http - "Open" button will be present*
4. Click "Open" - incorrect webpage will open
*Sometimes "open" button will be persistent, sometimes it disappears after few scans of non-http text

**Expected behavior**
Links without http should be either not recognized as links or script should check if link have http:// and add it if not (I'd prefer second option).

**Desktop (please complete the following information):**
 - W10 1909
 - Chrome 87

**Additional context**
Imho ideal way of dealing with this would be by using 3 buttons in popup:
1. Open as website 
    //checks if text is starting with http:// or https://, if not - adds http:// at the beginning of text and treats it as hyperlink
2. Copy to clipboard 
    //copies text to clipboard
3. Close 
    //closes popup without additional action

**Comment by gokulkrishh** [comment]
@Aramil-S Thanks for reporting. I will fix it when I get free time.

**Comment by gokulkrishh** [comment]
@Aramil-S #5 Fixed
