### ISSUE TITLE
Switch between multiple camera's

### ISSUE THREAD

**Issue by thibaultmol** [gokulkrishh/qrcodescan.in#4]
Hi,

It seems like the webapp doesn't have any feature to swtich between the front and back camera's?
(also would be nice if it auto selected the back camera, as that's usually the one that people use when scanning QR codes)

Tested on a Google Pixel 2: https://www.whatsmybrowser.org/b/H42RV

Cheers

**Comment by gokulkrishh** [comment]
@thibaultmol Just wondering how helpful it will be to scan from a front-facing camera. usually, people scan with a back camera.

**Comment by thibaultmol** [comment]
The weird thing (and reason why i asked) is because for some reason it didn't show the back camera for me. But the front camera instead. Really weird

**Comment by gokulkrishh** [comment]
@thibaultmol I see. Got your point.

**Comment by gokulkrishh** [comment]
@thibaultmol This issue should be fixed now. Feel free to reopen this issue if not. Thanks

**Comment by thibaultmol** [comment]
Seems like it's 'only' doing front camera now?
Default being back camera is fine, but being able to use the front camera
with a button would be nice

**Comment by gokulkrishh** [comment]
@thibaultmol I see. Thanks for the input. I am not sure having a front camera for scanning would be that useful but will keep this on an enhancement list.
